-- Feasibility rate by scenario.
-- Reads the Parquet file generated by pnpm analytics:aggregate.
select
  scenarioName,
  count(*) as runs,
  sum(case when feasible then 1 else 0 end) as feasibleRuns,
  round(100.0 * sum(case when feasible then 1 else 0 end) / count(*), 2) as feasibilityRatePct
from read_parquet('data/analytics/latest-runs.parquet')
group by scenarioName
order by scenarioName;
