-- Feasibility rate by scenario.
-- Replace the read_json_auto path with the JSONL file generated by pnpm analytics:run.
select
  scenarioName,
  count(*) as runs,
  sum(case when feasible then 1 else 0 end) as feasibleRuns,
  round(100.0 * sum(case when feasible then 1 else 0 end) / count(*), 2) as feasibilityRatePct
from read_json_auto('data/analytics/latest-runs.jsonl')
group by scenarioName
order by scenarioName;
