#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    import polars as pl
except ModuleNotFoundError as error:
    raise SystemExit(
        "Missing Python dependency: polars==1.14.0\n"
        "Install analytics dependencies with: pnpm analytics:setup"
    ) from error


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_dir = Path(args.output_dir)
    latest_output = Path(args.latest_output)
    run_date = args.run_date
    part_name = args.part_name

    if not input_path.exists():
        raise SystemExit(f"Input file not found: {input_path}")

    runs = pl.scan_ndjson(input_path)
    latest_output.parent.mkdir(parents=True, exist_ok=True)
    write_parquet(latest_output, runs)

    partitions = []
    scenario_frame = runs.select(pl.col("scenarioName").unique().sort()).collect()
    scenarios = scenario_frame.get_column("scenarioName").to_list()
    for scenario in scenarios:
        partition_path = output_dir / f"scenarioName={scenario}" / f"runDate={run_date}" / part_name
        partition_path.parent.mkdir(parents=True, exist_ok=True)
        write_parquet(partition_path, runs.filter(pl.col("scenarioName") == scenario))
        partitions.append(partition_path)

    print(
        json.dumps(
            {
                "input": str(input_path),
                "latestOutput": str(latest_output),
                "partitionedOutput": str(output_dir),
                "partitions": len(partitions),
            },
            indent=2,
        )
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write analytics runs as partitioned Parquet.")
    parser.add_argument("--input", required=True, help="JSONL runs file generated by analytics-run.")
    parser.add_argument("--output-dir", required=True, help="Root directory for partitioned Parquet output.")
    parser.add_argument("--latest-output", required=True, help="Compatibility Parquet output path.")
    parser.add_argument("--run-date", required=True, help="Run date partition value in YYYY-MM-DD format.")
    parser.add_argument("--part-name", required=True, help="Parquet part file name.")
    return parser.parse_args()


def write_parquet(path: Path, frame: pl.LazyFrame) -> None:
    if hasattr(frame, "sink_parquet"):
        try:
            frame.sink_parquet(path)
            return
        except pl.exceptions.InvalidOperationError:
            pass

    frame.collect().write_parquet(path)


if __name__ == "__main__":
    main()
